# Site
name: "UpLift Health Inc."
title: "UpLift | The Depression App That Works"
description: "Blog for essential depression information - created by UpLift, a science-based and effective app for depression relief."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.svg'
# baseurl: "/"
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  gaby:
    name: Gaby
    display_name: Gaby Buentello
    avatar: "assets/images/gaby.jpg"
    description: "Gaby is UpLift’s Content & Social Media Intern. She has a B.A. in Asian Studies and her background spans education consulting, digital marketing, and copywriting. She’s an avid language learner (having studied four so far) and enjoys playing piano in her free time."
  aislinn:
    name: Aislinn
    display_name: Aislinn Pluta
    avatar: "assets/images/aislinn.png"
    description: " Aislinn is UpLift's Content Director. She has a B.A. in Psychology and a Master's in Applied Positive Psychology, the scientific study of the factors that lead to a full and meaningful life."
  andrew:
    name: Andrew
    display_name: Andrew Gorrill
    avatar: "assets/images/andy.png"
    description: "Andrew has a diverse background, ranging from Chinese language and culture to organic agriculture. He occupies a variety of roles at UpLift, including customer service and project management."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, _example_posts]
